openapi: '3.0.2'
info:
  title: aimo_openapi
  version: '1.0'
servers:
  - url: https://api.server.test/v1
paths:
  /period:
    get:
      tags: 
      - "period"
      summary: "get annual period"
      responses:
        '200':
          description: OK          
          content:
            application/json:
              schema:
                type: array
                items:
                  properties:
                    id:
                      type: integer
                      format: int64
                    period:
                      type: string
                example:
                  - id: 1
                    period: 202105 
                  - id: 2
                    period: 202011
                  - id: 3
                    period: 202005 
