version: "3"

services:
  nginx:
    container_name: aimo_nginx
    build: 
      context: .
      dockerfile: ./nginx/Dockerfile
    ports:
      - "9000:80"
    volumes:
      - ./front/app:/aimo

  web:
    container_name: aimo_web
    build: ./front
    ports:
      - "9001:9001"
    privileged: true
    volumes:
      - ./front/app:/app
    tty: true
    stdin_open: true
    command: /bin/sh

  api:
    container_name: aimo_api
    build: ./back
    ports:
      - "9002:9002"
    volumes:
      - ./back/api:/github.com/j-kato732/aimo
    tty: true
    stdin_open: true

  swagger-ui:
    image: swaggerapi/swagger-ui
    ports:
      - "8081:8080"
    volumes:
      - ./swagger/aimo_openapi.yml:/swagger/aimo_openapi.yml
    environment:
      SWAGGER_JSON: /swagger/aimo_openapi.yml

  swagger-editor:
    image: swaggerapi/swagger-editor
    ports:
      - "8082:8080"
    volumes:
      - ./swagger/aimo_openapi.yml:/swagger/aimo_openapi.yml

  mock:
    image: stoplight/prism
    container_name: swagger_api
    ports:
      - "8000:4010"
    volumes:
      - ./swagger/aimo_openapi.yml:/swagger/aimo_openapi.yml
    command: mock -h 0.0.0.0 /swagger/aimo_openapi.yml

  sqlite-web:
    container_name: aimo_db_web
    build: ./sqlite-web
    ports:
      - "8001:8080"
    volumes:
      - ./back/api/db/test.db:/data/test.db
    command: sqlite_web -H 0.0.0.0 -x /data/test.db
