version: '3'

services:
    nginx:
        container_name: aimo_nginx
        build: ./nginx
        ports:
            - '9000:80'
        volumes:
            - ./front/app:/var/www/html
            - ./nginx/server.conf:/etc/nginx/nginx.conf

    web:
        container_name: aimo_web
        build: ./front
        ports:
            - '9001:9001'
        privileged: true
        volumes:
            - ./front/app:/app
        tty: true
        stdin_open: true
        command: /bin/sh

    swagger-ui:
      image: swaggerapi/swagger-ui
      ports:
        - '8081:8080'
      volumes:
        - ./swagger/aimo_openapi.yml:/swagger/aimo_openapi.yml
      environment:
        SWAGGER_JSON: /swagger/aimo_openapi.yml

    swagger-editor:
      image: swaggerapi/swagger-editor
      ports:
        - '8082:8080'
      volumes:
        - ./swagger/aimo_openapi.yml:/swagger/aimo_openapi.yml

    mock:
      image: stoplight/prism
      container_name: swagger_api
      ports:
        - '8000:4010'
      volumes:
        - ./swagger/aimo_openapi.yml:/swagger/aimo_openapi.yml
      command: mock -h 0.0.0.0 /swagger/aimo_openapi.yml

