version: "3"

services:
  nginx:
    container_name: aimo_nginx
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./front/app:/aimo
      - /etc/letsencrypt/live/www.aimo.tokyo/fullchain.pem:/etc/nginx/letsencrypt/fullchain.pem
      - /etc/letsencrypt/live/www.aimo.tokyo/privkey.pem:/etc/ngins/letsencrypt/privkey.pem
      - /var/log/nginx/access.log:/var/log/nginx/access.log

  api:
    container_name: aimo_api
    build: ./back
    ports:
      - "9002:9002"
    volumes:
      - ./back/api:/github.com/j-kato732/aimo
    tty: true
    stdin_open: true

volumes:
  https-portal-data: