version: "3"

services:
  nginx:
    container_name: aimo_nginx
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./front/app:/aimo
      - /var/log/nginx:/var/log/nginx

  api:
    container_name: aimo_api
    build: ./back
    ports:
      - "9002:9002"
    volumes:
      - ./back/api:/github.com/j-kato732/aimo
    tty: true
    stdin_open: true
    command: /github.com/j-kato732/aimo/startup.sh

