openapi: '3.0.2'
info:
  title: aimo_openapi
  version: '1.0'
servers:
  - url: http://api.server.test/v1
paths:
  /period:
    get:
      tags: 
      - "period"
      summary: "get annual period"
      responses:
        '200':
          description: OK          
          content:
            application/json:
              schema:
                type: array
                items:
                  properties:
                    id:
                      type: integer
                      format: int64
                    period:
                      type: string
                example:
                  - id: 1
                    period: 202005 
                  - id: 2
                    period: 202011
                  - id: 3
                    period: 202105 
  /aimoInfo/{exec_date}:
    get:
      tags:
      - "aimoInfo"
      summary: "get aimo inform"
      parameters:
      - name: exec_date
        in: path
        description: 取得対象日付
        required: true
        schema:
          $ref: '#/components/schemas/exec_date'
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/get_aimoInfo_response'
  /userInfo:
    get:
      tags:
      - "userInfo"
      summary: "get user information"
      parameters:
      - name: user_id
        in: query
        description: ユーザID
        required: true
        schema:
          $ref: '#/components/schemas/get_userInfo_request'
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  response:
                    $ref: '#/components/schemas/default_response'
                  result:
                    $ref: '#/components/schemas/get_userInfo_response'
                
          
components:
  schemas:
    exec_date:
      description: 実行日付
      type: string
      minLength: 10
      maxLength: 10
      example: 20210501
    get_aimoInfo_response:
      description: aimoお知らせ取得のレスポンス
      type: object
      properties:
        status:
          type: string
          example: 1
        message:
          type: string
        result:
          type: array
          items:
            type: object
            properties:
              inform_id:
                type: integer
                example: 1
              inform_content:
                type: string
                example: 目標入力期間になりました
    get_userInfo_request:
      description: ユーザ情報取得のリクエスト
      type: object
      properties:
        user_id:
          type: integer
          example: 1
        period:
          type: string
          example: 202105
    get_userInfo_response:
      description: ユーザ情報取得レスポンス
      type: object
      properties:
        userInfo:
          type: array
          items:
            type: object
            properties:
              user_id:
                type: integer
                example: 1
              last_name:
                type: string
                maxLength: 10
                example: kato
              first_name:
                type: string
                maxLength: 10
                example: jin
              department:
                type: string
                maxLength: 20
                example: ソリューション本部
              job:
                type: string
                maxLength: 20
                example: スタッフ
              enrollmentFlg:
                type: boolean
                example: true
              adminFlg:
                type: boolean
                example: false
    default_response:
      description: 基本レスポンス
      type: object
      properties:
        status:
          type: string
          example: 1
        message:
          type: string
                
          

