// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// AimoClient is the client API for Aimo service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AimoClient interface {
	GetAim(ctx context.Context, in *GetAimRequest, opts ...grpc.CallOption) (*GetAimResponse, error)
	PostAim(ctx context.Context, in *AimModel, opts ...grpc.CallOption) (*PostAimResponse, error)
	PutAim(ctx context.Context, in *AimModel, opts ...grpc.CallOption) (*PutAimResponse, error)
	GetAchievementMeans(ctx context.Context, in *AchievementMeanModel, opts ...grpc.CallOption) (*GetAchievementMeansResponse, error)
	PostAchievementMeans(ctx context.Context, in *PostAchievementMeansRequest, opts ...grpc.CallOption) (*PostAchievementMeansResponse, error)
	PutAchievementMeans(ctx context.Context, in *PutAchievementMeansRequest, opts ...grpc.CallOption) (*PutAchievementMeansResponses, error)
	GetAchievementMean(ctx context.Context, in *GetAchievementMeanRequest, opts ...grpc.CallOption) (*GetAchievementMeanResponse, error)
	PostAchievementMean(ctx context.Context, in *AchievementMeanModel, opts ...grpc.CallOption) (*PostAchievementMeanResponse, error)
	PutAchievementMean(ctx context.Context, in *AchievementMeanModel, opts ...grpc.CallOption) (*PutDefaultResponse, error)
}

type aimoClient struct {
	cc grpc.ClientConnInterface
}

func NewAimoClient(cc grpc.ClientConnInterface) AimoClient {
	return &aimoClient{cc}
}

func (c *aimoClient) GetAim(ctx context.Context, in *GetAimRequest, opts ...grpc.CallOption) (*GetAimResponse, error) {
	out := new(GetAimResponse)
	err := c.cc.Invoke(ctx, "/aimo.aimo/getAim", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aimoClient) PostAim(ctx context.Context, in *AimModel, opts ...grpc.CallOption) (*PostAimResponse, error) {
	out := new(PostAimResponse)
	err := c.cc.Invoke(ctx, "/aimo.aimo/postAim", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aimoClient) PutAim(ctx context.Context, in *AimModel, opts ...grpc.CallOption) (*PutAimResponse, error) {
	out := new(PutAimResponse)
	err := c.cc.Invoke(ctx, "/aimo.aimo/putAim", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aimoClient) GetAchievementMeans(ctx context.Context, in *AchievementMeanModel, opts ...grpc.CallOption) (*GetAchievementMeansResponse, error) {
	out := new(GetAchievementMeansResponse)
	err := c.cc.Invoke(ctx, "/aimo.aimo/getAchievementMeans", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aimoClient) PostAchievementMeans(ctx context.Context, in *PostAchievementMeansRequest, opts ...grpc.CallOption) (*PostAchievementMeansResponse, error) {
	out := new(PostAchievementMeansResponse)
	err := c.cc.Invoke(ctx, "/aimo.aimo/postAchievementMeans", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aimoClient) PutAchievementMeans(ctx context.Context, in *PutAchievementMeansRequest, opts ...grpc.CallOption) (*PutAchievementMeansResponses, error) {
	out := new(PutAchievementMeansResponses)
	err := c.cc.Invoke(ctx, "/aimo.aimo/putAchievementMeans", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aimoClient) GetAchievementMean(ctx context.Context, in *GetAchievementMeanRequest, opts ...grpc.CallOption) (*GetAchievementMeanResponse, error) {
	out := new(GetAchievementMeanResponse)
	err := c.cc.Invoke(ctx, "/aimo.aimo/getAchievementMean", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aimoClient) PostAchievementMean(ctx context.Context, in *AchievementMeanModel, opts ...grpc.CallOption) (*PostAchievementMeanResponse, error) {
	out := new(PostAchievementMeanResponse)
	err := c.cc.Invoke(ctx, "/aimo.aimo/postAchievementMean", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aimoClient) PutAchievementMean(ctx context.Context, in *AchievementMeanModel, opts ...grpc.CallOption) (*PutDefaultResponse, error) {
	out := new(PutDefaultResponse)
	err := c.cc.Invoke(ctx, "/aimo.aimo/putAchievementMean", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AimoServer is the server API for Aimo service.
// All implementations must embed UnimplementedAimoServer
// for forward compatibility
type AimoServer interface {
	GetAim(context.Context, *GetAimRequest) (*GetAimResponse, error)
	PostAim(context.Context, *AimModel) (*PostAimResponse, error)
	PutAim(context.Context, *AimModel) (*PutAimResponse, error)
	GetAchievementMeans(context.Context, *AchievementMeanModel) (*GetAchievementMeansResponse, error)
	PostAchievementMeans(context.Context, *PostAchievementMeansRequest) (*PostAchievementMeansResponse, error)
	PutAchievementMeans(context.Context, *PutAchievementMeansRequest) (*PutAchievementMeansResponses, error)
	GetAchievementMean(context.Context, *GetAchievementMeanRequest) (*GetAchievementMeanResponse, error)
	PostAchievementMean(context.Context, *AchievementMeanModel) (*PostAchievementMeanResponse, error)
	PutAchievementMean(context.Context, *AchievementMeanModel) (*PutDefaultResponse, error)
	mustEmbedUnimplementedAimoServer()
}

// UnimplementedAimoServer must be embedded to have forward compatible implementations.
type UnimplementedAimoServer struct {
}

func (UnimplementedAimoServer) GetAim(context.Context, *GetAimRequest) (*GetAimResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAim not implemented")
}
func (UnimplementedAimoServer) PostAim(context.Context, *AimModel) (*PostAimResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PostAim not implemented")
}
func (UnimplementedAimoServer) PutAim(context.Context, *AimModel) (*PutAimResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PutAim not implemented")
}
func (UnimplementedAimoServer) GetAchievementMeans(context.Context, *AchievementMeanModel) (*GetAchievementMeansResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAchievementMeans not implemented")
}
func (UnimplementedAimoServer) PostAchievementMeans(context.Context, *PostAchievementMeansRequest) (*PostAchievementMeansResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PostAchievementMeans not implemented")
}
func (UnimplementedAimoServer) PutAchievementMeans(context.Context, *PutAchievementMeansRequest) (*PutAchievementMeansResponses, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PutAchievementMeans not implemented")
}
func (UnimplementedAimoServer) GetAchievementMean(context.Context, *GetAchievementMeanRequest) (*GetAchievementMeanResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAchievementMean not implemented")
}
func (UnimplementedAimoServer) PostAchievementMean(context.Context, *AchievementMeanModel) (*PostAchievementMeanResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PostAchievementMean not implemented")
}
func (UnimplementedAimoServer) PutAchievementMean(context.Context, *AchievementMeanModel) (*PutDefaultResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PutAchievementMean not implemented")
}
func (UnimplementedAimoServer) mustEmbedUnimplementedAimoServer() {}

// UnsafeAimoServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AimoServer will
// result in compilation errors.
type UnsafeAimoServer interface {
	mustEmbedUnimplementedAimoServer()
}

func RegisterAimoServer(s grpc.ServiceRegistrar, srv AimoServer) {
	s.RegisterService(&Aimo_ServiceDesc, srv)
}

func _Aimo_GetAim_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAimRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AimoServer).GetAim(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/aimo.aimo/getAim",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AimoServer).GetAim(ctx, req.(*GetAimRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Aimo_PostAim_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AimModel)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AimoServer).PostAim(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/aimo.aimo/postAim",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AimoServer).PostAim(ctx, req.(*AimModel))
	}
	return interceptor(ctx, in, info, handler)
}

func _Aimo_PutAim_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AimModel)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AimoServer).PutAim(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/aimo.aimo/putAim",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AimoServer).PutAim(ctx, req.(*AimModel))
	}
	return interceptor(ctx, in, info, handler)
}

func _Aimo_GetAchievementMeans_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AchievementMeanModel)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AimoServer).GetAchievementMeans(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/aimo.aimo/getAchievementMeans",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AimoServer).GetAchievementMeans(ctx, req.(*AchievementMeanModel))
	}
	return interceptor(ctx, in, info, handler)
}

func _Aimo_PostAchievementMeans_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PostAchievementMeansRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AimoServer).PostAchievementMeans(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/aimo.aimo/postAchievementMeans",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AimoServer).PostAchievementMeans(ctx, req.(*PostAchievementMeansRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Aimo_PutAchievementMeans_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PutAchievementMeansRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AimoServer).PutAchievementMeans(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/aimo.aimo/putAchievementMeans",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AimoServer).PutAchievementMeans(ctx, req.(*PutAchievementMeansRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Aimo_GetAchievementMean_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAchievementMeanRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AimoServer).GetAchievementMean(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/aimo.aimo/getAchievementMean",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AimoServer).GetAchievementMean(ctx, req.(*GetAchievementMeanRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Aimo_PostAchievementMean_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AchievementMeanModel)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AimoServer).PostAchievementMean(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/aimo.aimo/postAchievementMean",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AimoServer).PostAchievementMean(ctx, req.(*AchievementMeanModel))
	}
	return interceptor(ctx, in, info, handler)
}

func _Aimo_PutAchievementMean_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AchievementMeanModel)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AimoServer).PutAchievementMean(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/aimo.aimo/putAchievementMean",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AimoServer).PutAchievementMean(ctx, req.(*AchievementMeanModel))
	}
	return interceptor(ctx, in, info, handler)
}

// Aimo_ServiceDesc is the grpc.ServiceDesc for Aimo service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Aimo_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "aimo.aimo",
	HandlerType: (*AimoServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "getAim",
			Handler:    _Aimo_GetAim_Handler,
		},
		{
			MethodName: "postAim",
			Handler:    _Aimo_PostAim_Handler,
		},
		{
			MethodName: "putAim",
			Handler:    _Aimo_PutAim_Handler,
		},
		{
			MethodName: "getAchievementMeans",
			Handler:    _Aimo_GetAchievementMeans_Handler,
		},
		{
			MethodName: "postAchievementMeans",
			Handler:    _Aimo_PostAchievementMeans_Handler,
		},
		{
			MethodName: "putAchievementMeans",
			Handler:    _Aimo_PutAchievementMeans_Handler,
		},
		{
			MethodName: "getAchievementMean",
			Handler:    _Aimo_GetAchievementMean_Handler,
		},
		{
			MethodName: "postAchievementMean",
			Handler:    _Aimo_PostAchievementMean_Handler,
		},
		{
			MethodName: "putAchievementMean",
			Handler:    _Aimo_PutAchievementMean_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/aimo.proto",
}
